service: real-boost-api-project
frameworkVersion: ">=1.1.0 <2.0.0"
custom:
  environment:
     stage: "${opt:stage, self:provider.stage}"
provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"
  stage: ${self:provider.environment.custom_stage}
  region: us-west-2
  environment:
    custom_stage: ${opt:stage}
functions:
  create_message:
    handler: endpoints/message/create.create
    events:
      - http:
          path: message/create
          method: get
          cors: true
  list_message:
    handler: endpoints/message/list.list
    events:
      - http:
          path: message/list
          method: get
          cors: true

resources:
  Resources:
    messageDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: uuid
            AttributeType: S

        KeySchema:
          -
            AttributeName: uuid
            KeyType: HASH

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: message-${self:custom.environment.stage}

